[[redirects]]
  force = true
  from = "/api/flickr/*"
  status = 200
  to = "https://www.flickr.com/services/rest/:splat"

[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200